# Generated by Django 6.0.6 on 2026-06-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(max_length=1000)),
                ('price_from', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
                ('monument_type', models.CharField(blank=True, max_length=80)),
                ('material', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_headquarters', models.BooleanField(default=False)),
                ('projects_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-is_headquarters', 'city'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('image_url', models.URLField(max_length=1000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_video', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('material', models.CharField(choices=[('granite', 'Гранит'), ('marble', 'Мрамор'), ('labradorite', 'Лабрадорит'), ('gabbro', 'Габбро')], max_length=32)),
                ('style', models.CharField(choices=[('classic', 'Классика'), ('modern', 'Минимализм'), ('author', 'Авторские')], max_length=32)),
                ('product_type', models.CharField(choices=[('single', 'Одиночные'), ('double', 'Двойные'), ('svo', 'СВО'), ('complex', 'Комплексы')], max_length=32)),
                ('material_label', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image_url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.CharField(blank=True, max_length=200)),
                ('finish', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
