# Generated by Django 6.0.6 on 2026-06-16 22:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officelocation',
            options={'ordering': ['-is_headquarters', '-is_highlighted', 'city']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at', 'sort_order']},
        ),
        migrations.AddField(
            model_name='officelocation',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officelocation',
            name='region',
            field=models.CharField(choices=[('krasnodar_krai', 'Краснодарский край'), ('adygea', 'Республика Адыгея'), ('other', 'Другие регионы')], default='krasnodar_krai', max_length=32),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
