# Generated by Django 6.0.6 on 2026-07-18 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_review_image_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Код страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('meta_title', models.CharField(blank=True, max_length=250, verbose_name='SEO-заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO-описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='extra_services',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.extraservice', verbose_name='Дополнительные услуги'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000, verbose_name='Ссылка на изображение')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='Описание изображения')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товара',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, verbose_name='Код блока')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на изображение')),
                ('button_label', models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Показывать блок')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.sitepage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страниц',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('page', 'key'), name='unique_content_block_key_per_page')],
            },
        ),
    ]
